from __future__ import annotations


class WSEvent:
    # Lifecycle
    READY = "READY"

    # Guild
    GUILD_CREATE = "GUILD_CREATE"
    GUILD_UPDATE = "GUILD_UPDATE"
    GUILD_DELETE = "GUILD_DELETE"

    # Guild members
    GUILD_MEMBER_ADD = "GUILD_MEMBER_ADD"
    GUILD_MEMBER_UPDATE = "GUILD_MEMBER_UPDATE"
    GUILD_MEMBER_REMOVE = "GUILD_MEMBER_REMOVE"

    # Channels
    CHANNEL_CREATE = "CHANNEL_CREATE"
    CHANNEL_UPDATE = "CHANNEL_UPDATE"
    CHANNEL_DELETE = "CHANNEL_DELETE"

    # Categories
    CATEGORY_CREATE = "CATEGORY_CREATE"
    CATEGORY_UPDATE = "CATEGORY_UPDATE"
    CATEGORY_DELETE = "CATEGORY_DELETE"

    # Messages
    MESSAGE_CREATE = "MESSAGE_CREATE"
    MESSAGE_UPDATE = "MESSAGE_UPDATE"
    MESSAGE_DELETE = "MESSAGE_DELETE"

    # Reactions
    REACTION_ADD = "REACTION_ADD"
    REACTION_REMOVE = "REACTION_REMOVE"

    # Typing
    TYPING_START = "TYPING_START"

    # Presence
    PRESENCE_UPDATE = "PRESENCE_UPDATE"

    # DMs
    DM_THREAD_CREATE = "DM_THREAD_CREATE"
    DM_MESSAGE_CREATE = "DM_MESSAGE_CREATE"

    # Voice / WebRTC signaling
    CALL_SIGNAL = "CALL_SIGNAL"
    VOICE_STATE_UPDATE = "VOICE_STATE_UPDATE"

    # Invites
    INVITE_CREATE = "INVITE_CREATE"
    INVITE_DELETE = "INVITE_DELETE"

    # Pins
    MESSAGE_PIN = "MESSAGE_PIN"
    MESSAGE_UNPIN = "MESSAGE_UNPIN"

    # Friends / social
    FRIEND_REQUEST_CREATE = "FRIEND_REQUEST_CREATE"
    FRIEND_REQUEST_UPDATE = "FRIEND_REQUEST_UPDATE"

    # User updates
    USER_UPDATE = "USER_UPDATE"

    # Webhooks
    WEBHOOK_CREATE = "WEBHOOK_CREATE"

    # Stage channels
    STAGE_UPDATE = "STAGE_UPDATE"

    # Screen sharing
    SCREEN_SHARE_START = "SCREEN_SHARE_START"
    SCREEN_SHARE_STOP = "SCREEN_SHARE_STOP"
